config/routes.rb
MappedArticles::Application.routes.draw do
  
  get "/" => "articles#index", as: "articles"
  
  get "articles" => "articles#reroute"
  
  get "articles/all" => "articles#all", as: "all_articles"
  
  get "articles/new" => "articles#new", as: "new_article" 
  
  post "/" => "articles#create" 
  
  get "articles/:id" => "articles#show", as: "article"
  
  get "articles/:id/edit" => "articles#edit", as: "edit_article"  
  
  put "articles/:id" => "articles#update"
  
  delete "articles/:id" => "articles#delete"
  
  get "about" => "application#about", as: "about"
  
  get "locations" => "locations#index", as: "locations"
  
  get "locations/:id" => "locations#show", as: "location"
  
  get "users/new" => "users#new", as: "new_user"
   
  post "users" => "users#create"
  
  get "users/login" => "users#login", as: "user_login"
  
  post "users/find" => "users#find"
  
  get "users" => "users#logout", as: "user_logout" 
  
  

end

app/views/shared/_locations_form.html.erb
<%= f.fields_for :pins, newPin, child_index: ruby_object_id do |p| %>

	<%= p.label "new_location_alias", 
				"Name for location (visible to readers):" %>
	<br>
	<%= p.text_field("new_location_alias") %>

	<br><br>

	<%= p.label "new_location_address", "Address:" %>
	<br>
	<%= p.text_field("new_location_address", size: 50) %>
	
<% end %>
<br>

app/views/shared/_main_nav.html.erb
<div id="nav_bar">
	<header class="nav">
    <div id="nav_title">
      <h1><%= link_to("Omaha Times", articles_path)%></h1>
    </div>
      
    <div id="nav_options">
  	  <ul id="nav">
  		  <li><%= link_to("More Stories", all_articles_path) %></li>
  		  <li><%= link_to("About", about_path) %></li>
  	   </ul>
	   
       <ul id="user_panel">
         <% if @user == nil || @user.username == nil %>
           <li><%= link_to("Sign Up", new_user_path) %></li>
         <% end  %>
         <% if @user == nil || @user.username == nil %>
  		     <li><%= link_to("Log In", user_login_path) %></li>
         <% end %>
         <% if @admin %><li class="admin_priv"><%= link_to("New Article", new_article_path) %></li><% end %>
  		   <% if @user && @user.username != nil %>
           <li><%= link_to("Sign Out", user_logout_path) %></li>
           <% end %>
  	   </ul>
		</div>
	</header>
  
  <div id="mobile_nav">
    <header class="mobile_nav_title">
        <h1><%= link_to("Omaha Times", articles_path)%></h1>

    	  <ul id="mobile_nav_menu">
    		  <li><a href="#"><img src="https://nccwsc.usgs.gov/sites/all/themes/usgs/images/menu.png"></a></li>
        </ul>
  </div>
  
</div>

app/views/shared/_mobile_article_show_nav.html.erb
<div class="mobile_show_menu" id="mobile_show_menu" style="display: none;">
  <ul>
    <li><%= link_to("More Stories", all_articles_path) %></li>
    <li><%= link_to("About", about_path) %></li>
		<% if @admin %><li class="admin_priv"><%= link_to("Edit Article", edit_article_path(@article.id)) %></li><% end %>
		<% if @admin %><li class="admin_priv"><%= link_to("Unpublish Article", article_path(@article.id), method: :delete, confirm: "Are you sure you want to unpublish this article? It will no longer appear on the site but can always be retrieved from the database.") %></li><% end %>
		<% if @user ==nil %><li><%= link_to("Sign Up", new_user_path) %></li><% end %>
		<% if @user ==nil %><li><%= link_to("Log In", user_login_path) %></li><% end %>
		<% if @user %><li><%= link_to("Sign Out", user_logout_path) %></li><% end %>
  </ul>
</div>

app/views/shared/_mobile_nav.html.erb
<div class="mobile_main_menu" id="mobile_main_menu" style="display: none;">
  <ul>
    <li><%= link_to("More Stories", all_articles_path) %></li>
    <li><%= link_to("About", about_path) %></li>
    <% if @admin %><li class="admin_priv"><%= link_to("New Article", new_article_path) %></li><% end %>
		<% if @user ==nil %><li><%= link_to("Sign Up", new_user_path) %></li><% end %>
		<% if @user ==nil %><li><%= link_to("Log In", user_login_path) %></li><% end %>
		<% if @user %><li><%= link_to("Sign Out", user_logout_path) %></li><% end %>
  </ul>
</div>

app/views/shared/_show_nav.html.erb
<div id="show_nav_bar">
	<header class="nav">
		<ul id="show_nav">
			<li class="home_link"><%= link_to("Omaha Times", articles_path)%></li>
			<li><%= link_to("More Stories", all_articles_path) %></li>
			<li><%= link_to("About", about_path) %></li>
		</ul>
		<ul id="show_user_panel">
			<li class="admin_priv"><%= link_to("Edit", edit_article_path(@article.id)) if @admin %></li>
			<li class="admin_priv"><%= link_to("Unpublish", article_path(@article.id), method: :delete, confirm: "Are you sure you want to unpublish this article? It will no longer appear on the site but can always be retrieved from the database.") if @admin %></li>
			<li><%= link_to("Sign Up", new_user_path) if @user == nil %></li>
			<li><%= link_to("Log In", user_login_path) if @user == nil %></li>
			<li><%= link_to("Sign Out", user_logout_path) if @user %></li>
		</ul>
	</header>
  
  <div id="mobile_nav">
    <header>
        <ul class="mobile_nav_show_title">
          <li class="home_link"><%= link_to("Omaha Times", articles_path)%></li>
        </ul>

    	  <ul id="mobile_nav_show_menu">
    		  <li><a href="#"><img src="https://nccwsc.usgs.gov/sites/all/themes/usgs/images/menu.png"></a></li>
        </ul>
  </div>

</div>